### ISSUE TITLE
Fail to checkout PR when a push -f is done to the PR while is being already built

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [janinko/ghprb#148]
This issue comes from https://issues.jenkins-ci.org/browse/JENKINS-22537

Please consult that issue for details. Here is the summary of the latest research.

The setup is a job using a configuration matrix (I'm not sure if this is strictly necessary to reproduce the problem though) with only one variable and 2 configurations (which is only the Ubuntu version to do the build). Then the ghprb plugin is activated and configured to trigger a build by the GH hook.

Steps to reproduce:
1. Create a dummy project in GitHub
2. Add a build script that is only a `sleep 60`
3. Configure the Jenkins job to build with the ghprb plugin
4. Create a PR
5. Change something in the PR (you can do a `git commit --amend` and just change the commit message)
6. While jenkins is building the job (sleeping), do a `git push -f` to your PR branch
7. Wait for Jenkins to finish the current build and start the new one
8. You should see the error now

The error (this is the console output for one of the configurations in the matrix, the other have the same error) is:

```
Started by upstream project "Test" build number 40
originally caused by:
 GitHub pull request #76 of commit 8e9a1ab00c82edf5f37b400f0a98b6476ba63b97 automatically merged.
Building in workspace .../jenkins/jobs/Test/workspace/Ubuntu/trusty
Cloning the remote Git repository
Cloning repository git@github.com:someuser/somerepo.git
Fetching upstream changes from git@github.com:someuser/somerepo.git
using GIT_SSH to set credentials GitHub leandro-lucarella-sociomantic
Fetching upstream changes from git@github.com:someuser/somerepo.git
using GIT_SSH to set credentials GitHub leandro-lucarella-sociomantic
Checking out Revision 0c2e9e245bd8d7329c3d8b91013d806f4b112687 (detached)
FATAL: Could not checkout null with start point 0c2e9e245bd8d7329c3d8b91013d806f4b112687
hudson.plugins.git.GitException: Could not checkout null with start point 0c2e9e245bd8d7329c3d8b91013d806f4b112687
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1448)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:896)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1411)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:652)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:561)
    at hudson.model.Run.execute(Run.java:1665)
    at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:246)
Caused by: hudson.plugins.git.GitException: Command "git checkout -f 0c2e9e245bd8d7329c3d8b91013d806f4b112687" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 0c2e9e245bd8d7329c3d8b91013d806f4b112687

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1276)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1253)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1249)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1065)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1075)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1443)
    ... 9 more
```

This is the console output for the _whole_ job (not one configuration in particular):

```
GitHub pull request #76 of commit 8e9a1ab00c82edf5f37b400f0a98b6476ba63b97 automatically merged.
ode environment variables.
Building in workspace .../jenkins/jobs/Test/workspace
Fetching changes from the remote Git repository
Fetching upstream changes from git@github.com:someuser/somerepo.git
using GIT_SSH to set credentials GitHub leandro-lucarella-sociomantic
Checking out Revision 142cbdfe90a5e7cf8e2ba44eb6c16b4b93bb2b93 (detached)
Cleaning workspace
Resetting working tree
Triggering trusty
Triggering saucy
trusty completed with result FAILURE
saucy completed with result FAILURE
Finished: FAILURE
```

**Comment by artembochkov** [comment]
Hi, all,
We also experience the same problem. We have a matrix job building a project for a 5 different configurations (platforms). 
Sometimes it fails like this for one configuration and works well for the rest ones:
FATAL: Could not checkout null with start point f11538533f716841f223abbf0cbe43a60a0590a8
12:53:31 hudson.plugins.git.GitException: Could not checkout null with start point f11538533f716841f223abbf0cbe43a60a0590a8

And if we rerun the job - all works fine.

**Comment by DeepDiver1975** [comment]
reported in Jenkins Jira as well - https://issues.jenkins-ci.org/browse/JENKINS-26748

**Comment by martyngigg** [comment]
We are also experiencing this problem with matrix jobs. The parent has the correct reference but then when it starts the child jobs it looks like it passes along an old sha1 from a previous merge and not the updated one.

Output from parent job
```
GitHub pull request #219 of commit 096f9835a3de34f1f8713cc0513845ff83f07e30 automatically merged.
Setting status of 096f9835a3de34f1f8713cc0513845ff83f07e30 to PENDING with url http://builds.mantidproject.org/job/pull_requests/509/ and message: Merged build started.
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/jobs/pull_requests/workspace@6
Cloning the remote Git repository
Cloning repository git://github.com/mantidproject/mantid.git
 > git init /var/lib/jenkins/jobs/pull_requests/workspace@6 # timeout=10
Fetching upstream changes from git://github.com/mantidproject/mantid.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress git://github.com/mantidproject/mantid.git +refs/heads/*:refs/remotes/origin/* # timeout=30
 > git config remote.origin.url git://github.com/mantidproject/mantid.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url git://github.com/mantidproject/mantid.git # timeout=10
Fetching upstream changes from git://github.com/mantidproject/mantid.git
 > git -c core.askpass=true fetch --tags --progress git://github.com/mantidproject/mantid.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=30
 > git rev-parse refs/remotes/origin/pr/219/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/219/merge^{commit} # timeout=10
Checking out Revision a66d7a5c5fb873ee28462a27cec0b79b131b6530 (refs/remotes/origin/pr/219/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a66d7a5c5fb873ee28462a27cec0b79b131b6530
 > git rev-list 9e5da46e719b86cc4e3679562cdf4bfa386c4b1c # timeout=10
First time build. Skipping changelog.
Triggering pull_requests » win7-build
Triggering pull_requests » ubuntu-14.04-build
Triggering pull_requests » fedora20-build
Triggering pull_requests » rhel6-build
Triggering pull_requests » osx-10.8-build
Configuration pull_requests » win7-build is still in the queue: Waiting for next available executor on win7-build
pull_requests » win7-build completed with result SUCCESS
pull_requests » ubuntu-14.04-build completed with result FAILURE
pull_requests » fedora20-build completed with result FAILURE
pull_requests » rhel6-build completed with result FAILURE
pull_requests » osx-10.8-build completed with result FAILURE
Setting status of 096f9835a3de34f1f8713cc0513845ff83f07e30 to FAILURE with url http://builds.mantidproject.org/job/pull_requests/509/ and message: Merged build finished.
Finished: FAILURE
```
It is checking out the merge HEAD of the pull request at `a66d7a5c5fb873ee28462a27cec0b79b131b6530`, which looks correct if I compare it to pulling down the `pull/219/merge` locally.

However, when the child builds start you see (snipped output)
```
Started by upstream project "pull_requests" build number 509
originally caused by:
 GitHub pull request #219 of commit 096f9835a3de34f1f8713cc0513845ff83f07e30 automatically merged.
[EnvInject] - Loading node environment variables.
Building remotely on ndav-builder2 (vm sphinx rhel6-build cades) in workspace /home/builder/jenkins-linode/workspace/pull_requests/label/rhel6-build
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git://github.com/mantidproject/mantid.git # timeout=10
Fetching upstream changes from git://github.com/mantidproject/mantid.git
 > git --version # timeout=10
 > git fetch --tags --progress git://github.com/mantidproject/mantid.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=30
Checking out Revision 9e5da46e719b86cc4e3679562cdf4bfa386c4b1c (refs/remotes/origin/pr/219/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 9e5da46e719b86cc4e3679562cdf4bfa386c4b1c
 > git rev-list 9e5da46e719b86cc4e3679562cdf4bfa386c4b1c # timeout=10
```
It is trying to checkout `9e5da46e719b86cc4e3679562cdf4bfa386c4b1c`, which is not the same as the parent job of the matrix. This seems like quite a significant bug.

**Comment by directhex** [comment]
@martyngigg ghprb is innocent, it's an upstream GitHub bug, as far as my analysis goes.

If you still have the workspaces from your failed builds, try "git log" on your build nodes - the tip of the branch they're on should be an auto-generated commit merging the branch and master. This commitid is in refs/remotes/origin/pr/*/merge.

There will be a discrepancy between what your successful nodes believe this commit should be, and what the failures think it should be. If you check the timestamp on the merge commits, they will differ - even though all nodes in the matrix job started simultaneously & git fetch'd simultaneously.

I filed a support issue with GitHub late last week, but have had nothing back on the topic.

**Comment by martyngigg** [comment]
@directhex Thanks for the update. I had spotted the differing commits but not the timestamps. 

Hopefully they will respond soon.

**Comment by jpsim** [comment]
Has anyone found a workaround for this issue? It's been a major problem for us whenever rebasing (which happens fairly often).

**Comment by leandro-lucarella-sociomantic** [comment]
On Mon, Mar 16, 2015 at 10:12:59AM -0700, JP Simard wrote:
> Has anyone found a workaround for this issue? It's been a major
> problem for us whenever rebasing (which happens fairly often).

I'm not having this problem often anymore, but when it happens usually
removing the last job results (and maybe a previous job too) and then
re-triggering the job (via a message in github) fixes the problem for
me.

**Comment by jpsim** [comment]
"Rebuild Last" always succeeds, but manually having to trigger builds kind of defeats the purpose of continuous integration.

**Comment by directhex** [comment]
I still haven't heard anything from Github, including when I put out feelers via internal contacts. The problem is at their end.

**Comment by mskutin** [comment]
Yeah, I've the same issue and it doesn't depend of git version. @jpsim Totally agree with you, "workaround" is manually clicking "Rebuild Last" button and definitely it's killing CI process.

**Comment by DeepDiver1975** [comment]
@janinko can we add a config switch to disable the whole merge mechanism?

As in we execute the job on the plain branch and leave it to the developers to rebase the branch if needed.

Thanks a lot!

**Comment by DavidTanner** [comment]
Check the readme, but there is an environment variable that gives you the original commit, not the test merge one.

**Comment by DeepDiver1975** [comment]
@DavidTanner I assume you are talking about this?

````
If you want to use the actual commit in the pull request, use ${ghprbActualCommit} instead of ${sha1}
````

Will this help with respect to this issue and NOT try to perform the merge at all?

**Comment by DavidTanner** [comment]
The merge happens because you created a pull request on a GitHub. This plugin just tells the git client what commit/branch/etc to use when it does the checkout portion.

**Comment by DeepDiver1975** [comment]
Thanks David. I take that as a no then. Too bad - these bloody issue is almost rendering this plugin unusable. :-(

**Comment by directhex** [comment]
It's a problem only with matrix jobs.

Here's what happens:

* "master" job of matrix gets executed, which determines the sha1 of the target commit (i.e. it turns pr/XXX/merge into abcdef1)
* the matrix slaves get scheduled to build this sha1sum
* the matrix slaves eventually execute the build

The race condition here is that because the PR merge commit is ephemeral (i.e. it gets recreated every time there's a commit to either the PR, or the repo the PR targets). If there's any commit between when the matrix master running and the matrix slaves running (e.g. if one of your matrix axis slaves is overloaded so the scheduling takes some time), the problem occurs because the commitid that the matrix master saw no longer exists by the time the matrix slaves fetch the repo.

The "easy" fix is to make sure matrix slaves build the merge ref, not the sha1. Or, as we did, don't use matrix jobs at all.

**Comment by DeepDiver1975** [comment]
Great input @directhex thx

That easy fix has to be implemented within the plugin? Or is this something we can somehow configure already as if today?

**Comment by DavidTanner** [comment]
@directhex you have it almost correct. 
The plugin doesn't actually do any git work, it just pulls the pull request from the GitHub api.  The data returned has a boolean flag that says wether the request is mergeable or not.

If it is mergeable, then ${sha1} = pr/###/merge, else ${sha1} = abcdef1, where abcdef1 is sha of last commit to the pull request when we queried the api.  

If ${sha1} is pr/###/merge, then the actual sha hash is resolved by the jenkins git plugin when checking out the workspace.

```final String commitSha = cause.isMerged() ? "origin/pr/" + cause.getPullID() + "/merge" : cause.getCommit();
        values.add(new StringParameterValue("sha1", commitSha)); ```

**Comment by mikemcquaid** [comment]
> The "easy" fix is to make sure matrix slaves build the merge ref, not the sha1. Or, as we did, don't use matrix jobs at all.

Nice debugging, folks. In my situation I have to use matrix builds. Is there any way of working around this currently by tweaking settings or will it need a bugfix in a future `ghprb` release? Thanks!

**Comment by thughes** [comment]
Just to clarify, it sounds like the underlying issue with matrix builds is that GitHub force pushes to the `pr/<id>/merge` ref when a new commit is added to the pull request. As a result, it's possible that the merge SHA1 that was resolved by `ghprb` will no longer be available for any git repos that hadn't fetched the original merge commit (e.g., a matrix job on a slave, etc).

Further expanding the code snippet from `ghprb` in the earlier commit, we have:
```
        final String commitSha = cause.isMerged() ? "origin/pr/" + cause.getPullID() + "/merge" : cause.getCommit();
        values.add(new StringParameterValue("sha1", commitSha));
        values.add(new StringParameterValue("ghprbActualCommit", cause.getCommit()));
```

This makes it look like you could avoid this problem by using `${ghprbActualCommit}` instead of `${sha1}`, since the former will be an actual commit in the pull request branch as opposed to an ephemeral commit that could be force-pushed over. Note that this could have other side effects in that the pull request branch could be build, but once merged into the target branch, the build could fail (since you're not building the merged branches). I think the only way to safely do a merged build would be to use the pull request commit and have `ghprb` do a local merge from the target branch. Note that for matrix builds to be consistent it would need to pass a SHA1 for the target branch as well so that any matrix jobs doing the local merge would use the exact same commits.

**Comment by childnode** [comment]
I'm experiencing this too after rebasing the development tree, it's old tip tree-ish id is evaluated for checkout even I prune / delete workspace completely, including git force clone.

My speculation: The plugin seems to evaluate the last successfull build for getting the id to calculate a diff?

what is strange to me and what let me find a fix/workaround for me:
This is the log from the last stable build where tip of develop was `@6bc8861` and `swd` was the given name for the remote
```
`Checking out Revision 6bc8861e2f988a8fe92b5dc4fa0a657982b98559 (swd/develop)
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f 6bc8861e2f988a8fe92b5dc4fa0a657982b98559
Using 'Changelog to branch' strategy.
fatal: bad revision '^origin/develop'
ERROR: Unable to retrieve changeset
[8mha:AAAAWB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0ldFVf2c+b/lb5MDAwVRQxSaBqcITRIIQMEMIIUFgAAckCEiWAAAAA=[0mhudson.plugins.git.GitException: Error launching git whatchanged
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:775)
	at hudson.plugins.git.GitSCM.computeChangeLog(GitSCM.java:1121)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1042)
	at hudson.scm.SCM.checkout(SCM.java:484)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
No emails were triggered.
```

this is the one from the failed one after rebasing and push forcing develop: 6bc8861 is no more the remote
```
Checking out Revision 6bc8861e2f988a8fe92b5dc4fa0a657982b98559 (swd/develop)
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f 6bc8861e2f988a8fe92b5dc4fa0a657982b98559
FATAL: Could not checkout null with start point 6bc8861e2f988a8fe92b5dc4fa0a657982b98559
[8mha:AAAAWB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0ldFVf2c+b/lb5MDAwVRQxSaBqcITRIIQMEMIIUFgAAckCEiWAAAAA=[0mhudson.plugins.git.GitException: Could not checkout null with start point 6bc8861e2f988a8fe92b5dc4fa0a657982b98559
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1855)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1033)
	at hudson.scm.SCM.checkout(SCM.java:484)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: hudson.plugins.git.GitException: Command "git.exe checkout -f 6bc8861e2f988a8fe92b5dc4fa0a657982b98559" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 6bc8861e2f988a8fe92b5dc4fa0a657982b98559

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1591)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:86)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1850)
	... 10 more
```

I checked back the git repository on the jenkins server:
```
C:\.jenkins\workspace\Build_Player\rep>git branch -av
  remotes/swd/develop                                                                           aa43a90 comment on develop tip
```

The error `fatal: bad revision '^origin/develop'` in log from "green" build let me check up the job config again which leads me to the misconfiguration made, that the remote was set up with a given name "swd" but the branch specifier to make tests for where set up with "origin/develop" and "origin/feature*". Somehow it worked still fine with this misconfig ... up today.

So: I fixed up the given name / id for the remote and changed it to origin and: anything working again! Perhaps this might help someone too, still I'm not sure / I expect the root-cause is somewhere else.

unfortunatly: all branches are rebuild, even they were build with the "wrong" configuration

**Comment by mihelich** [comment]
> The "easy" fix is to make sure matrix slaves build the merge ref, not the sha1.

We did exactly that to resolve this issue, which we were hitting probably a third(!) of the time. Patch against git (not ghprb) plugin 2.4.0:
```java
diff --git a/src/main/java/hudson/plugins/git/GitSCM.java b/src/main/java/hudson/plugins/git/GitSCM.java
index aca465d..bbddc53 100644
--- a/src/main/java/hudson/plugins/git/GitSCM.java
+++ b/src/main/java/hudson/plugins/git/GitSCM.java
@@ -915,6 +915,7 @@ public class GitSCM extends GitSCMBackwardCompatibility {
 
 
         // every MatrixRun should build the same marked commit ID
+        /*
         if (build instanceof MatrixRun) {
             MatrixBuild parentBuild = ((MatrixRun) build).getParentBuild();
             if (parentBuild != null) {
@@ -926,6 +927,7 @@ public class GitSCM extends GitSCMBackwardCompatibility {
                 }
             }
         }
+        */
 
         // parameter forcing the commit ID to build
         if (candidates.isEmpty() ) {
```

The patch just bluntly disables the git plugin's special case logic for matrix builds, so each child will use `pr/<id>/merge`. It introduces a risk of child builds using inconsistent commits, but in practice hasn't caused us any problems.

I posted this also on [JENKINS-26290](https://issues.jenkins-ci.org/browse/JENKINS-26290), where hopefully a better fix can be found. I suspect an optimal solution would require changes to both plugins.

**Comment by jdart** [comment]
Using ${ghprbActualCommit} instead of ${sha1} seems to be a decent work around for my team. We were having this issue using the MultiJob jenkins.

**Comment by adelyafatykhova** [comment]
Hi everyone. We switched to using ${ghprbActualCommit} but the problem still stands. The initial parent-child jobs works just fine, but on the second run the parent has the correct details but the child job fails from trying to checkout the wrong commit. In our case oftentimes there are new commits in the pull request while the first PR job is still running, hence the failure. Are there any further solutions/advice/experience for what to do in this situation?

**Comment by rmmh** [comment]
There's a separate, similar-looking bug in the Git plugin that causes a "reference is not a tree" failure, unrelated to matrix builds or push -f. There's a potential fix in [JENKINS-2629](https://issues.jenkins-ci.org/browse/JENKINS-26290#comment-269569).

The characteristic error is that the build is supposed to test "origin/pr/123/merge", and then proceeds to fail to checkout a different PR's branch, like "origin/pr/345/merge", resulting in `fatal: reference is not a tree`. It happens on retests of a merge commit, see the linked bug for more information.
